name: Build Core

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # windows
          - goos: windows
            goarch: amd64
            goamd64: v3
            suffix: ".exe"
          - goos: windows
            goarch: arm64
            suffix: ".exe"
          # linux
          - goos: linux
            goarch: amd64
            goamd64: v3
            suffix: ""
          - goos: linux
            goarch: arm64
            suffix: ""
          # darwin
          - goos: darwin
            goarch: amd64
            goamd64: v3
            suffix: ""
          - goos: darwin
            goarch: arm64
            suffix: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOAMD64: ${{ matrix.goamd64 }}
          TAGS: with_quic,with_dhcp,with_wireguard,with_utls,with_clash_api,with_gvisor,with_conntrack
          VERSION: ${{ github.ref_name }}
        run: |
          echo "Using version: ${VERSION}"
          if [ "${{ matrix.goarch }}" = "amd64" ]; then
            FILENAME=sing-box-${VERSION}-${{ matrix.goos }}-${{ matrix.goarch }}-v3${{ matrix.suffix }}
          else
            FILENAME=sing-box-${VERSION}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }}
          fi
          
          mkdir -p build
           go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags ${TAGS} -o ./build/$FILENAME ./cmd/sing-box
          
          cd build
          zip -r $FILENAME.zip $FILENAME
          
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "ZIP_FILE=$FILENAME.zip" >> $GITHUB_ENV

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: sing-box ${{ github.ref_name }}
          files: ./build/${{ env.ZIP_FILE }}
          draft: false
          prerelease: false
          generate_release_notes: false